In [1]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [2]:
import numpy as np

In [3]:
A = np.arange(12)

In [4]:
B = A

In [5]:
B

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
B.shape = (3,4)

In [8]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
B

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
B[::2,] = 0

In [11]:
B

array([[0, 0, 0, 0],
       [4, 5, 6, 7],
       [0, 0, 0, 0]])

In [12]:
A

array([[0, 0, 0, 0],
       [4, 5, 6, 7],
       [0, 0, 0, 0]])

In [13]:
A = np.arange(12).reshape(3,4)

In [14]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
C = A.view()

In [16]:
C is A

False

In [17]:
C.flags.owndata

False

In [18]:
C

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
C.shape = (2,6)

In [20]:
C

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [21]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
A[0,] = [10,20,30,40]

In [23]:
A

array([[10, 20, 30, 40],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
C

array([[10, 20, 30, 40,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [25]:
A = np.arange(12).reshape(3,4)

In [26]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
S = A[:, 1:3]

In [28]:
S

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [29]:
S[:,1] = 100

In [30]:
S

array([[  1, 100],
       [  5, 100],
       [  9, 100]])

In [31]:
A

array([[  0,   1, 100,   3],
       [  4,   5, 100,   7],
       [  8,   9, 100,  11]])

In [32]:
A = np.arange(12).reshape(3,4)

In [33]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
D = A.copy()

In [35]:
D is A

False

In [36]:
D.shape = (2,6)

In [37]:
D

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [38]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
D[0, :] = [0,0,0,0,0,0]

In [40]:
D

array([[ 0,  0,  0,  0,  0,  0],
       [ 6,  7,  8,  9, 10, 11]])

In [41]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])