In [1]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [2]:
import numpy as np

In [3]:
A = np.arange(12)**2

In [4]:
A

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [5]:
A[2]

4

In [6]:
A[2:6]

array([ 4,  9, 16, 25])

In [7]:
i = np.array([1,1,3,8,5])

In [8]:
A[i]

array([ 1,  1,  9, 64, 25])

In [9]:
j = np.array([[3,4],[9,7]])

In [10]:
A[j]

array([[ 9, 16],
       [81, 49]])

In [11]:
A = np.arange(12).reshape(3,4)

In [12]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
A[np.array([[0,1],[1,2]]),]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [14]:
A[np.array([[0,1],[1,2]]), np.array([[2,1],[3,3]])]

array([[ 2,  5],
       [ 7, 11]])

In [15]:
A = np.arange(5)

In [16]:
A

array([0, 1, 2, 3, 4])

In [17]:
A[[1,3,4]] = 0

In [18]:
A

array([0, 0, 2, 0, 0])

In [19]:
A[1] = 100

In [20]:
A[1,3,4] = 10

IndexError: too many indices for array: array is 1-dimensional, but 3 were indexed

In [21]:
A = np.arange(5)

In [22]:
A

array([0, 1, 2, 3, 4])

In [23]:
A[[0,0,2]] = [10,20,30]

In [24]:
A

array([20,  1, 30,  3,  4])

In [25]:
A = np.arange(5)

In [26]:
A[[0,0,2]] += 1

In [27]:
A

array([1, 1, 3, 3, 4])

In [28]:
A = np.array([2,3,4,5])
B = np.array([8,5,4])

In [29]:
np.ix_(A, B)

(array([[2],
        [3],
        [4],
        [5]]),
 array([[8, 5, 4]]))

In [30]:
A = np.array([2,3,4,5])
B = np.array([8,5,4])
C = np.array([5,4,6,8,3])

In [31]:
np.ix_(A,B,C)

(array([[[2]],
 
        [[3]],
 
        [[4]],
 
        [[5]]]),
 array([[[8],
         [5],
         [4]]]),
 array([[[5, 4, 6, 8, 3]]]))

In [32]:
AX, BX = np.ix_(A,B)

In [33]:
AX + BX

array([[10,  7,  6],
       [11,  8,  7],
       [12,  9,  8],
       [13, 10,  9]])

In [34]:
#A + B * C

In [35]:
AX, BX, CX = np.ix_(A,B,C)

In [36]:
AX + BX * CX

array([[[42, 34, 50, 66, 26],
        [27, 22, 32, 42, 17],
        [22, 18, 26, 34, 14]],

       [[43, 35, 51, 67, 27],
        [28, 23, 33, 43, 18],
        [23, 19, 27, 35, 15]],

       [[44, 36, 52, 68, 28],
        [29, 24, 34, 44, 19],
        [24, 20, 28, 36, 16]],

       [[45, 37, 53, 69, 29],
        [30, 25, 35, 45, 20],
        [25, 21, 29, 37, 17]]])

In [37]:
A = np.array([2,3,4,5])
B = np.array([8,5,4])

In [38]:
def reduce_func(*arrs, func=np.add):
    aix = np.ix_(*arrs)
    result = aix[0]
    for item in aix[1:]:
        result = func(result, item)
    return result

In [39]:
A

array([2, 3, 4, 5])

In [40]:
B

array([8, 5, 4])

In [41]:
reduce_func(A,B)

array([[10,  7,  6],
       [11,  8,  7],
       [12,  9,  8],
       [13, 10,  9]])

In [42]:
reduce_func(A,B, func=np.divide)

array([[0.25 , 0.4  , 0.5  ],
       [0.375, 0.6  , 0.75 ],
       [0.5  , 0.8  , 1.   ],
       [0.625, 1.   , 1.25 ]])

In [43]:
A = np.arange(20).reshape(4,5)

In [44]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [45]:
A % 2 == 0

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False]])

In [46]:
A[A%2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [47]:
A[A%2==0] = A[A%2==0]**2

In [48]:
A

array([[  0,   1,   4,   3,  16],
       [  5,  36,   7,  64,   9],
       [100,  11, 144,  13, 196],
       [ 15, 256,  17, 324,  19]])

In [49]:
A[A%2==0] = 0

In [50]:
A

array([[ 0,  1,  0,  3,  0],
       [ 5,  0,  7,  0,  9],
       [ 0, 11,  0, 13,  0],
       [15,  0, 17,  0, 19]])