In [1]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [2]:
import numpy as np

In [3]:
A = np.arange(15).reshape(3,5)

In [4]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
A.ndim

2

In [6]:
A.shape

(3, 5)

In [7]:
A.size

15

In [8]:
A.dtype

dtype('int32')

In [9]:
A.itemsize

4

In [10]:
A = np.arange(12).reshape(3,4)

In [11]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
A.dtype

dtype('int32')

In [13]:
A.dtype = np.int64

In [14]:
A

array([[ 4294967296, 12884901890],
       [21474836484, 30064771078],
       [38654705672, 47244640266]], dtype=int64)