In [132]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [2]:
import numpy as np

In [3]:
A = np.array([2,3,4])

In [4]:
A

array([2, 3, 4])

In [5]:
A.dtype

dtype('int32')

In [6]:
B = np.array([1.2, 3.5, 5.1])

In [7]:
B.dtype

dtype('float64')

In [8]:
C = np.array([[1,2], [3,4]], dtype=complex)

In [9]:
C

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [10]:
D = np.array(C, copy=False)

In [11]:
id(C), id(D)

(2474953398320, 2474953398320)

In [12]:
E = np.array(A, copy=True)

In [13]:
id(E), id(A)

(2474953398896, 2474948747376)

In [14]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.ones((2,3,4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [16]:
np.empty((2,3))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [4.22790856e-307, 1.42413555e-306, 1.78019082e-306]])

In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(11,20)

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [19]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [20]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [21]:
np.linspace(0,2)

array([0.        , 0.04081633, 0.08163265, 0.12244898, 0.16326531,
       0.20408163, 0.24489796, 0.28571429, 0.32653061, 0.36734694,
       0.40816327, 0.44897959, 0.48979592, 0.53061224, 0.57142857,
       0.6122449 , 0.65306122, 0.69387755, 0.73469388, 0.7755102 ,
       0.81632653, 0.85714286, 0.89795918, 0.93877551, 0.97959184,
       1.02040816, 1.06122449, 1.10204082, 1.14285714, 1.18367347,
       1.2244898 , 1.26530612, 1.30612245, 1.34693878, 1.3877551 ,
       1.42857143, 1.46938776, 1.51020408, 1.55102041, 1.59183673,
       1.63265306, 1.67346939, 1.71428571, 1.75510204, 1.79591837,
       1.83673469, 1.87755102, 1.91836735, 1.95918367, 2.        ])

In [22]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [23]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [24]:
x = np.linspace(0, 2*np.pi, 100)

In [25]:
y = np.sin(x)

In [26]:
A = np.arange(12).reshape(3,4)

In [27]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
A.shape

(3, 4)

In [29]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [30]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
A.reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [32]:
A.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [33]:
A.resize(2,6)

In [34]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [35]:
A.shape

(2, 6)

In [36]:
A.shape = (3,4)

In [37]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
A.reshape(2,-1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [39]:
A.resize(4,-1)

ValueError: negative dimensions not allowed

In [40]:
A = np.arange(6)

In [41]:
print(A)

[0 1 2 3 4 5]


In [42]:
A

array([0, 1, 2, 3, 4, 5])

In [43]:
B = np.arange(12).reshape(4,3)

In [44]:
print(B)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [45]:
C = np.arange(24).reshape(2,3,4)

In [46]:
C

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [47]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [48]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [49]:
np.set_printoptions(threshold=10000)

In [50]:
print(np.arange(100).reshape(10,10))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [51]:
A = np.array([20,30,40,50])

In [52]:
B = np.arange(4)

In [53]:
A

array([20, 30, 40, 50])

In [54]:
B

array([0, 1, 2, 3])

In [55]:
A - B

array([20, 29, 38, 47])

In [56]:
[1,2,3]*2

[1, 2, 3, 1, 2, 3]

In [57]:
A * 2

array([ 40,  60,  80, 100])

In [58]:
B ** 2

array([0, 1, 4, 9])

In [59]:
10 * np.sin(A)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [60]:
A < 35

array([ True,  True, False, False])

In [61]:
A = np.array([[1,1], [0,1]])

In [62]:
B = np.array([[2,0], [3,4]])

In [63]:
A * B

array([[2, 0],
       [0, 4]])

In [64]:
A @ B

array([[5, 4],
       [3, 4]])

In [65]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [66]:
A = np.ones((2,3), dtype=int)

In [67]:
B = np.random.random((2,3))

In [68]:
A

array([[1, 1, 1],
       [1, 1, 1]])

In [69]:
B

array([[0.66595146, 0.93292544, 0.11686739],
       [0.67846659, 0.84355947, 0.89022945]])

In [70]:
A *= 3

In [71]:
A

array([[3, 3, 3],
       [3, 3, 3]])

In [72]:
B += 3

In [73]:
B

array([[3.66595146, 3.93292544, 3.11686739],
       [3.67846659, 3.84355947, 3.89022945]])

In [74]:
A += B

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

In [75]:
A = np.ones(3, dtype=np.int32)

In [76]:
B = np.linspace(0, np.pi, 3)

In [77]:
B.dtype

dtype('float64')

In [78]:
C = A+B

In [79]:
C.dtype

dtype('float64')

In [80]:
A = np.random.random((2,3))

In [81]:
A

array([[0.74329503, 0.9377589 , 0.01528603],
       [0.55912471, 0.59353371, 0.66052207]])

In [82]:
A.sum(), A.min(), A.max()

(3.5095204477534647, 0.015286029422053704, 0.9377589041495666)

In [83]:
np.sum(A)

3.5095204477534647

In [84]:
A = np.arange(12).reshape(3,4)

In [85]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [86]:
A.sum(axis=0)

array([12, 15, 18, 21])

In [87]:
np.sum(A, axis=0)

array([12, 15, 18, 21])

In [88]:
A.sum(axis=1)

array([ 6, 22, 38])

In [89]:
B = np.arange(24).reshape(2,3,4)

In [90]:
B

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [91]:
B[1,2,1]

21

In [92]:
B.sum()

276

In [93]:
B.sum(axis=0)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [94]:
B.sum(axis=1)

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [95]:
B

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [96]:
B.sum(axis=2)

array([[ 6, 22, 38],
       [54, 70, 86]])

In [97]:
A = np.arange(12).reshape(3,4)

In [98]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [99]:
A.sum(axis=0)

array([12, 15, 18, 21])

In [100]:
A = np.arange(3)

In [101]:
B = np.arange(4,7)

In [102]:
A

array([0, 1, 2])

In [103]:
B

array([4, 5, 6])

In [104]:
A + B

array([4, 6, 8])

In [105]:
np.add(A, B)

array([4, 6, 8])

In [106]:
id(A), id(B)

(2474965941584, 2474953396400)

In [107]:
np.add(A, B, A)

array([4, 6, 8])

In [108]:
A

array([4, 6, 8])

In [109]:
id(A)

2474965941584

In [110]:
A = np.arange(3)
B = np.arange(4,7)
C = np.array([20,30,40])

In [111]:
A

array([0, 1, 2])

In [112]:
B

array([4, 5, 6])

In [113]:
C

array([20, 30, 40])

In [114]:
G = A*B + C

In [115]:
T1 = A * B
G = T1 + C
del T1

In [116]:
G = A * B
np.add(G, C, G)

array([20, 35, 52])

In [117]:
G = A * B
G += C

In [118]:
A = np.array([1,2,3])

In [119]:
B = np.array([2,2,2])

In [120]:
A * B

array([2, 4, 6])

In [121]:
np.multiply(A, B)

array([2, 4, 6])

In [122]:
A

array([1, 2, 3])

In [123]:
B = 2

In [124]:
A * B

array([2, 4, 6])

In [125]:
A = np.array([[0,0,0], 
              [10,10,10], 
              [20,20,20], 
              [30,30,30]])

In [126]:
B = np.array([1,2,3])

In [127]:
A + B

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [128]:
A = np.array([0,10,20,30])
B = np.array([1,2,3])

In [129]:
A[:, np.newaxis]

array([[ 0],
       [10],
       [20],
       [30]])

In [130]:
B

array([1, 2, 3])

In [131]:
A[:, np.newaxis] + B

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])