In [90]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [2]:
import numpy as np

In [3]:
A = np.arange(10)**3

In [4]:
A

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [5]:
A[0]

0

In [6]:
A[2]

8

In [7]:
A[-1]

729

In [8]:
A[-2]

512

In [9]:
A[10]

IndexError: index 10 is out of bounds for axis 0 with size 10

In [10]:
A[2:5]

array([ 8, 27, 64], dtype=int32)

In [11]:
A[0:7:2]

array([  0,   8,  64, 216], dtype=int32)

In [12]:
A[::2]

array([  0,   8,  64, 216, 512], dtype=int32)

In [13]:
A[::-1]

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0], dtype=int32)

In [14]:
A[:6:2] = -1000

In [15]:
A

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729], dtype=int32)

In [16]:
B = np.arange(20).reshape(5,4)

In [17]:
B

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [18]:
B[2,3]

11

In [19]:
B[-3, -1]

11

In [20]:
C = np.arange(24).reshape(2,3,4)

In [21]:
C

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [22]:
C[0,1,2]

6

In [23]:
C[1,2,3]

23

In [24]:
B

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [25]:
B[0:5, 1]

array([ 1,  5,  9, 13, 17])

In [26]:
B[:, 1]

array([ 1,  5,  9, 13, 17])

In [27]:
B[ , 1]

SyntaxError: invalid syntax (1614358907.py, line 1)

In [28]:
B[1]

array([4, 5, 6, 7])

In [29]:
B

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [30]:
B[:, 1]

array([ 1,  5,  9, 13, 17])

In [31]:
C

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [32]:
C[:, 0:2, 1:3]

array([[[ 1,  2],
        [ 5,  6]],

       [[13, 14],
        [17, 18]]])

In [33]:
C[,0:2, 1:3]

SyntaxError: invalid syntax (3531007762.py, line 1)

In [34]:
C[:, 0:2]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19]]])

In [35]:
C[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [36]:
C[0:2]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [37]:
A = np.arange(12).reshape(3,4)

In [38]:
B = np.arange(12,24).reshape(3,4)

In [39]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
B

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [41]:
np.vstack((A,B))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [42]:
np.hstack((A,B))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [43]:
np.dstack((A,B))

array([[[ 0, 12],
        [ 1, 13],
        [ 2, 14],
        [ 3, 15]],

       [[ 4, 16],
        [ 5, 17],
        [ 6, 18],
        [ 7, 19]],

       [[ 8, 20],
        [ 9, 21],
        [10, 22],
        [11, 23]]])

In [44]:
A = np.array((1,2,3,4))
B = np.array((5,6,7,8))
C = np.array((9,10,11,12))

In [45]:
A

array([1, 2, 3, 4])

In [46]:
B

array([5, 6, 7, 8])

In [47]:
C

array([ 9, 10, 11, 12])

In [48]:
np.column_stack((A,B,C))

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [49]:
np.hstack((A,B))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [50]:
A[:, np.newaxis]

array([[1],
       [2],
       [3],
       [4]])

In [51]:
np.hstack((A[:, np.newaxis], 
           B[:,np.newaxis]))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [52]:
np.row_stack((A,B))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [53]:
np.vstack((A,B))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [54]:
A = np.arange(12).reshape(3,4)
B = np.arange(12,24).reshape(3,4)

In [55]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [56]:
B

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [57]:
np.stack((A,B), axis=0)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [58]:
np.stack((A,B), axis=1)

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

In [59]:
np.stack((A,B), axis=2)

array([[[ 0, 12],
        [ 1, 13],
        [ 2, 14],
        [ 3, 15]],

       [[ 4, 16],
        [ 5, 17],
        [ 6, 18],
        [ 7, 19]],

       [[ 8, 20],
        [ 9, 21],
        [10, 22],
        [11, 23]]])

In [60]:
A = np.array((1,2,3,4))
B = np.array((5,6,7,8))
C = np.array((9,10,11,12))

In [61]:
A

array([1, 2, 3, 4])

In [62]:
B

array([5, 6, 7, 8])

In [63]:
C

array([ 9, 10, 11, 12])

In [64]:
np.r_[A,B,C]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [65]:
np.c_[A,B,C]

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [66]:
A = np.arange(12).reshape(3,4)

In [67]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [68]:
np.vsplit(A, 3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [69]:
np.vsplit(A, 3)[0]

array([[0, 1, 2, 3]])

In [70]:
np.hsplit(A, 2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [71]:
np.hsplit(A, 4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [72]:
B = np.arange(24).reshape(2,3,4)

In [73]:
B

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [74]:
np.dsplit(B, 2)

[array([[[ 0,  1],
         [ 4,  5],
         [ 8,  9]],
 
        [[12, 13],
         [16, 17],
         [20, 21]]]),
 array([[[ 2,  3],
         [ 6,  7],
         [10, 11]],
 
        [[14, 15],
         [18, 19],
         [22, 23]]])]

In [75]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [76]:
np.split(A, 3, axis=0)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [77]:
np.split(A, 2, axis=1)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [78]:
np.hsplit(A, 2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [79]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [80]:
A = np.arange(24).reshape(3,8)

In [81]:
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [82]:
np.hsplit(A, (2,5,6))

[array([[ 0,  1],
        [ 8,  9],
        [16, 17]]),
 array([[ 2,  3,  4],
        [10, 11, 12],
        [18, 19, 20]]),
 array([[ 5],
        [13],
        [21]]),
 array([[ 6,  7],
        [14, 15],
        [22, 23]])]

In [83]:
A = np.arange(12).reshape(3,4)

In [84]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [85]:
np.split(A, 2, axis=1)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [86]:
np.array_split(A, 2, axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]])]

In [87]:
A = np.arange(10)

In [88]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
np.array_split(A, 4)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7]), array([8, 9])]